version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laravel_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
